name: Deploy Chrome Extension

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: GoogleChrome/chrome-extension-tools-action@v1
        with:
          action: build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: gbahigdgjjlnmepmljlojjadijlcmfdl.chromiumapp.org
